### ISSUE TITLE
2020-Q1 Cache ASGS 2016 data type counts don't match

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/loci-cache-scripts#46]
Running pyloci tests, detected some mismatching ASGS 2016 MB features. 

|  Type | 2019 Cache count   | 2020 Cache  Count | asgsld.net counts | 
|---|---|---|---|
| MB  |  358009   |   315007    |  358,009  |  

It seems like not all the MBs were harvested and put into the cache? This issue is to investigate this disrecpency.

This is problematic as many of our crosswalking tools need the MBs to be there. 

Spot checking this MB (http://linked.data.gov.au/dataset/asgs2016/meshblock/20394030000) isn't in the new cache, but exists (located in the middle of Melbourne CBD)...

See http://3.104.29.122/sparql?name=&infer=true&sameAs=true&query=select+*%0Awhere+%7B%0A++++%3Chttp%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fasgs2016%2Fmeshblock%2F20394030000%3E+%3Fp+%3Fo%0A%7D

**Comment by jyucsiro** [comment]
Some digging into which MBs are in the prod vs dev cache and diffs. Wrote a script to list the MBs in each cache. Outputs of prod, dev and diffs in this zip file:

[mb_2016_cache_diffs.zip](https://github.com/CSIRO-enviro-informatics/loci-cache-scripts/files/4519632/mb_2016_cache_diffs.zip)

```
$ wc -l *_mb.txt
  315007 dev_cache_mb.txt
  358009 prod_cache_mb.txt
   43002 diff_cache_mb.txt
```

The easiest thing might be to harvest the list mb in the diff file and add them to the cache?

**Comment by jyucsiro** [comment]
According to ABS, 

> The 2016 ASGS contains 358,122 Mesh Blocks covering the whole of Australia without gaps or overlaps. This includes 113 non spatial Mesh Blocks special purpose codes, for Migratory-Offshore-Shipping and No Usual Address for the States and Territories. These non-spatial Mesh Blocks do not have a geographic boundary defining their extent and include areas that are difficult to define in this way.


https://www.abs.gov.au/ausstats/abs@.nsf/Lookup/by%20Subject/1270.0.55.001~July%202016~Main%20Features~Mesh%20Blocks%20(MB)~10012

**Comment by benjaminleighton** [comment]
I've downloaded https://s3-ap-southeast-2.amazonaws.com/loci-assets/asgs-20200226/asgs2016_meshblocks.nt.gz which I believe is the source of the meshblocks in the new cache. On unzipping it and running 
`grep -e .*10016330000.* asgs2016_meshblocks.nt` to search for one of the meshblocks in diff_cache_mb.txt (from you zip file) returns nothing 
but executing
`grep -e .*10000010000.* asgs2016_meshblocks.nt` to search for one of the meshblocks in the dev_cache_mb.txt returns a whole bunch of triples

I think this means that not all the meshblocks have been harvested correctly from the asgs ldapi https://asgsld.net/2016 
http://linked.data.gov.au/dataset/asgs2016/meshblock/10016330000 is present there but not in the dump. 

I'm not sure how easy it is to reharvest a select set of meshblocks out of the ldapi or filter them out of a new dump, but, if we can fix the harvest problem, then we could potentially upload the whole lot into the test cache as a stop gap. We might end up with duplicated triples, I'm not sure how much of a problem that will cause. 

@ashleysommer  can you comment on whether it looks like the problem is with harvesting and if so what might be wrong?

**Comment by ashleysommer** [comment]
If we have a known set of missing instances, I can add a new function to the harvester to harvest just a subset given the list

**Comment by jyucsiro** [comment]
Current task is to reharvest ASGS and load them into the new cache with complete set of MB, and updated relationships to STE.

**Comment by jyucsiro** [comment]
Done now
